### ISSUE TITLE
api is down

### ISSUE THREAD

**Issue by TheSpirit** [ThisIsBenny/rki-vaccination-data#13]
Hi.
Your api seems to be down.

**Comment by ThisIsBenny** [comment]
Hi, it is working for me:
![B98E5FA7-6946-4828-A883-8EFB85E0986E](https://user-images.githubusercontent.com/66417262/105047140-3e1c3000-5a6a-11eb-9e12-ffe2642e77f8.jpeg)

**Comment by TheSpirit** [comment]
hmm.
but if i open
https://rki-vaccination-data.vercel.app/api
via browser, i get an error.
<img width="694" alt="Bildschirmfoto 2021-01-19 um 15 27 44" src="https://user-images.githubusercontent.com/6056918/105047682-ea5e1680-5a6a-11eb-854d-e26b2f15f6ac.png">

and "lastUpdate" in your image should also show the 18th since there is also new data available

**Comment by ThisIsBenny** [comment]
you are write. I got a cached response. the RKI changed again the excel sheet.
Fix is on the way.

**Comment by TheSpirit** [comment]
thanks a lot for your work

**Comment by ThisIsBenny** [comment]
fix is online

![137F9494-2047-44C7-9ED9-83CD4B95866B](https://user-images.githubusercontent.com/66417262/105048461-e7aff100-5a6b-11eb-9999-20eae69a928c.jpeg)

**Comment by TheSpirit** [comment]
i still get no new data. is there some problem again?
Thanks

**Comment by ThisIsBenny** [comment]
@TheSpirit no the API is running. The cache isn't revalidate yet.
I will delete the cache with #17 and then it should works.
The cache has a TTL of 2 hours, so if the new excel will be uploaded, the in the worstcase, you will see the updated data 2 h later.

**Comment by TheSpirit** [comment]
Thanks

**Comment by ThisIsBenny** [comment]
@TheSpirit i have added a timestamp to the response header.
This timestamp will be also cached, so it is a good indicator to see from when the data is in the response. if you calculate +2 h you know when the cache is updated. please note the timezone (+1 h for germany)


you can see in this screenshot that the cache is 32min old:
![155BD4A8-69AC-4C5E-8B04-F46D0C14872B](https://user-images.githubusercontent.com/66417262/106749874-5faf1700-6627-11eb-9112-204148dc76be.jpeg)
