### ISSUE TITLE
2nd_vaccination data value for Germany - currently states only

### ISSUE THREAD

**Issue by Besenwiesler** [ThisIsBenny/rki-vaccination-data#15]
It seems the new 2nd_vaccination value is only available for the individual states. Would be great if the sum of all states would be available as a field for Germany. The Excel sheet contains the sum also, so I guess it should be a rather easy thing to add.

Anyway, thanks for the great API!

**Comment by ThisIsBenny** [comment]
Done :-)

**Comment by Besenwiesler** [comment]
Thanks!!
