### ISSUE TITLE
How often does the JSON data get updated?

### ISSUE THREAD

**Issue by Estradamis** [ThisIsBenny/rki-vaccination-data#2]
Hey @ThisIsBenny thanks for this awesome offer! As the RKI data has been updated today at 08:30 but the API (https://rki-vaccination-data.vercel.app/api) still provides dates from yesterday I wanted to ask how often this data gets updated.

Thanks a lot

**Comment by ThisIsBenny** [comment]
Hi @Estradamis the API returns the data from today, but the RKI miss to update the Date in the excel sheet (see tab), why the API say that the data are from yesterday:
<img width="931" alt="Bildschirmfoto 2020-12-31 um 13 06 09" src="https://user-images.githubusercontent.com/66417262/103409863-04da5980-4b69-11eb-8ff9-ca64157c3ee4.png">

In General: The API always loads the newest Data from the RKI with each request. But i use a Network-Cache with a TTL of 1 hour to prevent the RKI Server from too much load.
That means the first request loads new data and write this data to a cache. All request after the first one will get the response from the cache. the first request after one hour still receives the data from the cache, but triggers a cache update in the background. Thus, the second request that comes after an hour receives the new data.

If the cache update fails, the old cache will still be delivered. This prevents the clients from noticing anything about the error.

**Comment by Estradamis** [comment]
Alright, thanks a lot for your feedback 👍
