### ISSUE TITLE
RKI added column for AstraZeneca

### ISSUE THREAD

**Issue by therealrandallflagg** [ThisIsBenny/rki-vaccination-data#24]
Hi,

the RKI added a new column for the 'AstraZeneca' vaccine, so  'difference_to_the_previous_day' and all others columns behind this position are not working anymore.

**Comment by ThisIsBenny** [comment]
thanks for the hint. I'm working on a fix (#25). In three weeks i can provide the next fix, because they added only for the first vaccination a 'astrazeneca' column...
