### ISSUE TITLE
Missing data of Mecklenburg-Vorpommern

### ISSUE THREAD

**Issue by Viet2503** [ThisIsBenny/rki-vaccination-data#26]
As of today (12.02.2021), Mecklenburg-Vorpommern only contains key "total". Other keys like "rs", "vaccinated", "vaccinated_by_accine", etc. are missing. 

`"Mecklenburg-Vorpommern": {"total": 1608138}, "Niedersachsen":`

Is something wrong with parsing data for Mecklenburg-Vorpommern?

**Comment by ThisIsBenny** [comment]
Hi @Viet2503,

the RKI added a ' *' after the name in the excel, why the mapping isn't working anymore:
<img width="179" alt="Bildschirmfoto 2021-02-12 um 17 18 23" src="https://user-images.githubusercontent.com/66417262/107793355-7e638b00-6d56-11eb-8443-e95f25eeaa75.png">

The code will already remove the * but the whitespace between and * is new and now a problem. I will fix it.
