### ISSUE TITLE
Difference to the previous day is wrong

### ISSUE THREAD

**Issue by TheSpirit** [ThisIsBenny/rki-vaccination-data#28]
Hi. 
If I look at your data the value for
difference_to_the_previous_day = 208569
if I look at the excel sheet from rki (where you are getting your data from I think):
difference_to_the_previous_day = 269345
Maybe they changed again something in the format. 
Thanks

**Comment by ThisIsBenny** [comment]
<img width="1680" alt="Bildschirmfoto 2021-03-12 um 14 33 23" src="https://user-images.githubusercontent.com/66417262/110947210-2497b600-8340-11eb-8212-06d646553ce4.png">

yes, i take the numbers from the Excel. I have download the new excel version and there is the same number.

**Comment by TheSpirit** [comment]
@i thought difference to the previous day is first and second vaccination together

**Comment by ThisIsBenny** [comment]
no, i do not add the values in the api. this can be done in the app.
unfortunately a lot has been changed in excel, so the response structure doesn't look that great anymore. but i don't want to make any breaking changes

**Comment by TheSpirit** [comment]
Thx

**Comment by TheSpirit** [comment]
I have found the error. For the second vaccination the value of difference to the previous day in your api is getting the wrong column. You take the value from column „second vaccination and then astra Zeneca“ which is one column before the correct column „second vaccination and the difference to the previous day“. 
Please check. 
the value you show is 132 and the correct one is in the next column and should be 60776. 
Thanks

Here is the error:

states[state]['2nd_vaccination']['difference_to_the_previous_day'] = row[12].value
      
Is wrong. Correct would be

states[state]['2nd_vaccination']['vaccinated_by_accine']['astrazeneca'] = row[12].value
states[state]['2nd_vaccination']['difference_to_the_previous_day'] = row[13].value


Please check #29
