### ISSUE TITLE
New Astrazeneca column for 2nd vaccination

### ISSUE THREAD

**Issue by therealrandallflagg** [ThisIsBenny/rki-vaccination-data#29]
Hi @ThisIsBenny,
like expected there is now a new column for Astrazeneca for the 2nd vaccination.

Thx in advance!

<img width="394" alt="image" src="https://user-images.githubusercontent.com/78804669/110990300-6beb6a00-8373-11eb-8316-94a8e3dbe2ae.png">

**Comment by TheSpirit** [comment]
Here is the error:

states[state]['2nd_vaccination']['difference_to_the_previous_day'] = row[12].value

Is wrong. Correct would be

states[state]['2nd_vaccination']['vaccinated_by_accine']['astrazeneca'] = row[12].value
states[state]['2nd_vaccination']['difference_to_the_previous_day'] = row[13].value

Please see #28

**Comment by ThisIsBenny** [comment]
Done 😊

**Comment by therealrandallflagg** [comment]
👍🏻

**Comment by TheSpirit** [comment]
Thanks
