### ISSUE TITLE
Incorrect Date

### ISSUE THREAD

**Issue by DevQuandt** [ThisIsBenny/rki-vaccination-data#3]
The RKI did not update the name of the sheet. The only source where the date is correct is on their page https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html

just FYI

**Comment by ThisIsBenny** [comment]
Hi @DevQuandt thank you, i have already noticed it: #2 
I hope that the RKI did a better job in the future, i already got some messages where the user told me that the data are not up to date. But only the date in the API response is not up to date.
