### ISSUE TITLE
"scrapping data from RKI excel failed" - Perhaps due to new layout of RKI excel sheet

### ISSUE THREAD

**Issue by Viet2503** [ThisIsBenny/rki-vaccination-data#31]
Hey @ThisIsBenny,

just wanted to create this issue to let you know that as of today, scraping the RKI excel sheet fails, probably because of a new layout in the sheet. 

If I find time today, I can fix that for sure :)

Have a nice day!

**Comment by ThisIsBenny** [comment]
Hi @Viet2503, thanks for the hint. I will have a look on it.

**Comment by ThisIsBenny** [comment]
@Viet2503 issue is fixed 😊

**Comment by Viet2503** [comment]
Thanks for fixing! @ThisIsBenny  :)

Unfortunately there seems to be a bug with scraping data for Thüringen.  Numbers for vaccinations by vaccine type are missing here. 

End of API JSON:
`"Th\u00fcringen": {"total": 2133378}}, "vaccinated": 6966082, "2nd_vaccination": {"vaccinated": 197754, "difference_to_the_previous_day": 328615}, "sum_vaccine_doses": 7163836, "difference_to_the_previous_day": 4597478, "vaccinations_per_1000_inhabitants": 83.76, "total": 83166711, "quote": 8.38}`

**Comment by einstweilen** [comment]
@ThisIsBenny 
The data is still messed up. 

e.g. "Bayern" 
difference_to_the_previous_day:  820570 (should be: 36116)
quote: 783482
etc. 

2021-04-08, 15:05
 "Bayern": {"total": 13124737, "rs": "09", "vaccinated": 1155316, "vaccinated_by_accine": {"biontech": 92528, "moderna": 482057, "astrazeneca": 36116}, "difference_to_the_previous_day": 820570, "vaccinations_per_1000_inhabitants": 88.03, "quote": 783482, "2nd_vaccination": {"vaccinated": 36988, "vaccinated_by_accine": {"biontech": 100, "moderna": 13445, "astrazeneca": 89523}, "difference_to_the_previous_day": 59487, "quote": 73}}

Thank you in advance!

**Comment by ThisIsBenny** [comment]
@Viet2503 they have added a new row in the header rows, why the loop ends by "Schleswig-Holstein".

this fix the issue: https://github.com/ThisIsBenny/rki-vaccination-data/commit/25940b3646dae118e488a77539d2f2eb36b53ff5

and fix is available on dev stage: https://rki-vaccination-data-git-develop-thisisbenny.vercel.app/api

I will check all values in detail if there are any other changes.

**Comment by ThisIsBenny** [comment]
@einstweilen they have reordered the columns and added new columns, why the values are not correct anymore.

**Comment by ThisIsBenny** [comment]
issues will be fixed with #34
