### ISSUE TITLE
new layout of excel sheet

### ISSUE THREAD

**Issue by makeiteazy** [ThisIsBenny/rki-vaccination-data#33]
Hi @ThisIsBenny,

the data from the api is wrong since RKI changed their excel sheet.

Examples:
- vaccination quota is 8.3% in api, but must be 13.8%
- total vaccinated is too low
- 2nd vaccination value and quota is also too low
- column order of vaccine changed (total, biontech, moderna, astrazeneca)
- difference to previous day is much higher than it should be

Thanks in advance!

**Comment by ThisIsBenny** [comment]
Hi @makeiteazy, thanks for the hint.
I had assumed that only the order of the sheets was changed in today's Excel.
I will work on a fix

**Comment by ThisIsBenny** [comment]
issues will be fixed with #34
