### ISSUE TITLE
API not available 

### ISSUE THREAD

**Issue by TheSpirit** [ThisIsBenny/rki-vaccination-data#43]
Hi. 
If I try to open
`https://rki-vaccination-data.vercel.app/api/v2 `
I get the following info and no json
![94F88CEF-C279-4730-9281-517FCB10B20D](https://user-images.githubusercontent.com/6056918/132897077-af9200f1-6724-43aa-aa96-20febd35f4ca.jpeg)

**Comment by ThisIsBenny** [comment]
Hi @TheSpirit the RKI has changed the excel sheet structure again... I will have a look on it.

**Comment by TheSpirit** [comment]
Thanks

**Comment by ThisIsBenny** [comment]
fixed
