### ISSUE TITLE
Falsche Daten

### ISSUE THREAD

**Issue by TheSpirit** [ThisIsBenny/rki-vaccination-data#45]
Hi.
Du hast gestern ja deine API an das neue Excel Format angepasst.
Dabei ist dir leider ein Fehler unterlaufen.
Habe das ganze gerade mal versucht zu finden und ich glaube ich habe es.
Habe das ganze mal für Bayern gemacht.
Bei fullyVaccinated und dann differenceToThePrerviousDay hast du 20123 stehen.
Siehe hier:
<img width="576" alt="Bildschirmfoto 2021-09-11 um 19 35 30" src="https://user-images.githubusercontent.com/6056918/132956393-29b3073b-144b-4005-b09e-4f8e778c8427.png">
Laut Excel vom RKI sollten da aber 
15987 stehen.
<img width="1244" alt="Bildschirmfoto 2021-09-11 um 19 36 32" src="https://user-images.githubusercontent.com/6056918/132956398-d05a738e-9eef-4ff7-812b-53c0f03f58cb.png">
Die 20123 findet man eine Spalte weiter bei gesamt und nicht bei Differenz zum Vortag.

Deine Quote für die fullyVaccinated ist leider auch falsch berechnet.
Wenn du in der ExcelTabelle schaut stehen bei den Zweitimpfungen nicht mehr die Impfungen von Janssen. Diese werden nur bei den Erstimpfungen gezeigt.
Diese musst du aber für die Berechnung dazuzählen.
Vergleiche hierzu einfachmal in der Exceltabelle die Werte in Blatt eins Zelle E5 mit dem Wert in Tabellenblatte 2 Zelle I5. Die Differenz aus beiden ist in Blatt 2 Zelle G5 zu finden und das sind genau die "Erstimpfungen" von Janssen.

Und einen Wunsch hätte ich auch noch gleich:
Die Auffrischungsimpfungen müsste man ja auch noch dazu nehmen, da ich auch ausrechnen, wieviel jeden Tag gesamt geimpft wurde.
Danke

**Comment by ThisIsBenny** [comment]
Hi @TheSpirit ich habe an den Bezug der Impfdaten nichts geändert. Das Problem gestern war, dass das Datum der Daten früher mit im Tab Namen stand und dass das RKI es von dort entfernt hat. Ich beziehe deshalb das Datum nun aus dem ersten Tab. Aber scheinbar hat das RKI mehr geändert als ich auf dem ersten Blick erkennen konnte. Auffrischungsimpfungen gab es in der alten Version z.B. nicht. Ich schaue mir das mal nochmal im Detail ab.

**Comment by ThisIsBenny** [comment]
Problem ist behoben. Sollte gleich wieder alles richtig sein, sobald das Update ausgespielt ist.
Bezüglich der Auffrischungsimpfungen: Mich wundert, dass hier AstraZeneca nicht mit aufgeführt ist.
Ich würde warten bis die Liste vollständig ist, damit ich in X Tagen nicht wieder dran muss, weil man dann die Spalte für AstraZeneca hinzugefügt hat.

**Comment by TheSpirit** [comment]
Klar
