### ISSUE TITLE
Fully vacinated number far too low

### ISSUE THREAD

**Issue by thkukuk** [ThisIsBenny/rki-vaccination-data#47]
Since September 10th or so the fully vaccinated number is far too low.
As example for Germany, September 13th: the API/v2 says 58.58% are fully vaccinated, while the RKI dashboard says 62,2 %.

**Comment by TheSpirit** [comment]
The janssen vaccine is missing in the calculation since they are only mentioned in the section „vaccinated once“ and not in „fully vaccinated“.

**Comment by ThisIsBenny** [comment]
Hi, I get the values for the quotes from the totals columns and do not calculate the total by my own. It shouldn't have an impact that the janseen column missing. So the totals are coming from the RKI. Maybe the RKI use a different Inhabitants number.

**Comment by ThisIsBenny** [comment]
I have check the excel again. The second total is not anymore fully vaccinated as before. I will add jansen to the second total which is on the api the field "fullyVaccinated"

**Comment by TheSpirit** [comment]
then your calculation of the quote should be fine again
