### ISSUE TITLE
Hospitalization rate

### ISSUE THREAD

**Issue by Besenwiesler** [ThisIsBenny/rki-vaccination-data#49]
As you did such a wonderful job with the vaccination data, here comes the feature request to also cover the hospitalization rate. RKI data is available as a a csv file [here on GitHub](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland).

This does not really cover the current scope of a vaccination data API. However, as the hospitalization rate grows more important, I thought I at least ask. Client scripts could then easily use the hospitalization data.

**Comment by Besenwiesler** [comment]
Found [this API](https://api.corona-zahlen.org/docs/) for the hospitalization rate.

**Comment by ThisIsBenny** [comment]
Hi @Besenwiesler sorry for the late response. Nice to see that you find a API for your purpose. At the moment, i didn't have time for topic likes this due to personal reasons. Regards Benny

**Comment by Besenwiesler** [comment]
Hi @ThisIsBenny - no worries, the other API is fine for this purpose.

Hope all is well! Kind regards
