### ISSUE TITLE
Booster vaccinations

### ISSUE THREAD

**Issue by Besenwiesler** [ThisIsBenny/rki-vaccination-data#50]
The raw data published by the RKI now has columns for the booster vaccinations. Would be great if this could be added to the API.

**Comment by Viet2503** [comment]
I'll add that now :) 

Pull request should come in shortly, if I don't face any major obstacles.

**Comment by ThisIsBenny** [comment]
Hi @Viet2503  thanks for your support.

**Comment by Viet2503** [comment]
Changes should be done now. Fell free to revise it :)

#51

**Comment by ThisIsBenny** [comment]
@Viet2503  i have merge your pull request without checking it 🙈 the api breaks, why i have revert the merge.

**Comment by Viet2503** [comment]
@ThisIsBenny 

Shit, a comma is missing. Let me fix that quickly.

**Comment by Viet2503** [comment]
Hopefully it is fixed now. Do you crate a new PR from my develop branch? @ThisIsBenny 
Or should I do that?

**Comment by ThisIsBenny** [comment]
@Viet2503 you can do this. you will then also see a vercel deployment. you can use this url to verify that everything is working
